name = "Taproots"
uuid = "6cca9763-2e92-47b9-bf40-ccfe60418944"
version = "0.3.0"
authors = ["TyronCameron <tyron.luke.cameron@gmail.com>"]

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ResumableFunctions = "c5292f4c-5179-55e1-98c5-05642aab7184"
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"

[compat]
AbstractTrees = "^0.4.5"
GraphRecipes = "^0.5.13"
Plots = "^1.40.13"
ResumableFunctions = "1.0.4"
Term = "2"
julia = "1.10"
